//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Protocolo1.WSOperaciones {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="WSOperaciones.WSOperacionesSoap")]
    public interface WSOperacionesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento obtenerModuloResult del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/obtenerModulo", ReplyAction="*")]
        Protocolo1.WSOperaciones.obtenerModuloResponse obtenerModulo(Protocolo1.WSOperaciones.obtenerModuloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/obtenerModulo", ReplyAction="*")]
        System.Threading.Tasks.Task<Protocolo1.WSOperaciones.obtenerModuloResponse> obtenerModuloAsync(Protocolo1.WSOperaciones.obtenerModuloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento telefono del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/obtenerLlavesPublica", ReplyAction="*")]
        Protocolo1.WSOperaciones.obtenerLlavesPublicaResponse obtenerLlavesPublica(Protocolo1.WSOperaciones.obtenerLlavesPublicaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/obtenerLlavesPublica", ReplyAction="*")]
        System.Threading.Tasks.Task<Protocolo1.WSOperaciones.obtenerLlavesPublicaResponse> obtenerLlavesPublicaAsync(Protocolo1.WSOperaciones.obtenerLlavesPublicaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento telefono del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/VerificarCertificado", ReplyAction="*")]
        Protocolo1.WSOperaciones.VerificarCertificadoResponse VerificarCertificado(Protocolo1.WSOperaciones.VerificarCertificadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/VerificarCertificado", ReplyAction="*")]
        System.Threading.Tasks.Task<Protocolo1.WSOperaciones.VerificarCertificadoResponse> VerificarCertificadoAsync(Protocolo1.WSOperaciones.VerificarCertificadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerModuloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerModulo", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Protocolo1.WSOperaciones.obtenerModuloRequestBody Body;
        
        public obtenerModuloRequest() {
        }
        
        public obtenerModuloRequest(Protocolo1.WSOperaciones.obtenerModuloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class obtenerModuloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public obtenerModuloRequestBody() {
        }
        
        public obtenerModuloRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerModuloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerModuloResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Protocolo1.WSOperaciones.obtenerModuloResponseBody Body;
        
        public obtenerModuloResponse() {
        }
        
        public obtenerModuloResponse(Protocolo1.WSOperaciones.obtenerModuloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class obtenerModuloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerModuloResult;
        
        public obtenerModuloResponseBody() {
        }
        
        public obtenerModuloResponseBody(string obtenerModuloResult) {
            this.obtenerModuloResult = obtenerModuloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerLlavesPublicaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerLlavesPublica", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Protocolo1.WSOperaciones.obtenerLlavesPublicaRequestBody Body;
        
        public obtenerLlavesPublicaRequest() {
        }
        
        public obtenerLlavesPublicaRequest(Protocolo1.WSOperaciones.obtenerLlavesPublicaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class obtenerLlavesPublicaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string telefono;
        
        public obtenerLlavesPublicaRequestBody() {
        }
        
        public obtenerLlavesPublicaRequestBody(string telefono) {
            this.telefono = telefono;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerLlavesPublicaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerLlavesPublicaResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Protocolo1.WSOperaciones.obtenerLlavesPublicaResponseBody Body;
        
        public obtenerLlavesPublicaResponse() {
        }
        
        public obtenerLlavesPublicaResponse(Protocolo1.WSOperaciones.obtenerLlavesPublicaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class obtenerLlavesPublicaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerLlavesPublicaResult;
        
        public obtenerLlavesPublicaResponseBody() {
        }
        
        public obtenerLlavesPublicaResponseBody(string obtenerLlavesPublicaResult) {
            this.obtenerLlavesPublicaResult = obtenerLlavesPublicaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarCertificadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarCertificado", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Protocolo1.WSOperaciones.VerificarCertificadoRequestBody Body;
        
        public VerificarCertificadoRequest() {
        }
        
        public VerificarCertificadoRequest(Protocolo1.WSOperaciones.VerificarCertificadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class VerificarCertificadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string telefono;
        
        public VerificarCertificadoRequestBody() {
        }
        
        public VerificarCertificadoRequestBody(string telefono) {
            this.telefono = telefono;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarCertificadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarCertificadoResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public Protocolo1.WSOperaciones.VerificarCertificadoResponseBody Body;
        
        public VerificarCertificadoResponse() {
        }
        
        public VerificarCertificadoResponse(Protocolo1.WSOperaciones.VerificarCertificadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class VerificarCertificadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificarCertificadoResult;
        
        public VerificarCertificadoResponseBody() {
        }
        
        public VerificarCertificadoResponseBody(bool VerificarCertificadoResult) {
            this.VerificarCertificadoResult = VerificarCertificadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSOperacionesSoapChannel : Protocolo1.WSOperaciones.WSOperacionesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSOperacionesSoapClient : System.ServiceModel.ClientBase<Protocolo1.WSOperaciones.WSOperacionesSoap>, Protocolo1.WSOperaciones.WSOperacionesSoap {
        
        public WSOperacionesSoapClient() {
        }
        
        public WSOperacionesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSOperacionesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOperacionesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOperacionesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Protocolo1.WSOperaciones.obtenerModuloResponse Protocolo1.WSOperaciones.WSOperacionesSoap.obtenerModulo(Protocolo1.WSOperaciones.obtenerModuloRequest request) {
            return base.Channel.obtenerModulo(request);
        }
        
        public string obtenerModulo(int id) {
            Protocolo1.WSOperaciones.obtenerModuloRequest inValue = new Protocolo1.WSOperaciones.obtenerModuloRequest();
            inValue.Body = new Protocolo1.WSOperaciones.obtenerModuloRequestBody();
            inValue.Body.id = id;
            Protocolo1.WSOperaciones.obtenerModuloResponse retVal = ((Protocolo1.WSOperaciones.WSOperacionesSoap)(this)).obtenerModulo(inValue);
            return retVal.Body.obtenerModuloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Protocolo1.WSOperaciones.obtenerModuloResponse> Protocolo1.WSOperaciones.WSOperacionesSoap.obtenerModuloAsync(Protocolo1.WSOperaciones.obtenerModuloRequest request) {
            return base.Channel.obtenerModuloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Protocolo1.WSOperaciones.obtenerModuloResponse> obtenerModuloAsync(int id) {
            Protocolo1.WSOperaciones.obtenerModuloRequest inValue = new Protocolo1.WSOperaciones.obtenerModuloRequest();
            inValue.Body = new Protocolo1.WSOperaciones.obtenerModuloRequestBody();
            inValue.Body.id = id;
            return ((Protocolo1.WSOperaciones.WSOperacionesSoap)(this)).obtenerModuloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Protocolo1.WSOperaciones.obtenerLlavesPublicaResponse Protocolo1.WSOperaciones.WSOperacionesSoap.obtenerLlavesPublica(Protocolo1.WSOperaciones.obtenerLlavesPublicaRequest request) {
            return base.Channel.obtenerLlavesPublica(request);
        }
        
        public string obtenerLlavesPublica(string telefono) {
            Protocolo1.WSOperaciones.obtenerLlavesPublicaRequest inValue = new Protocolo1.WSOperaciones.obtenerLlavesPublicaRequest();
            inValue.Body = new Protocolo1.WSOperaciones.obtenerLlavesPublicaRequestBody();
            inValue.Body.telefono = telefono;
            Protocolo1.WSOperaciones.obtenerLlavesPublicaResponse retVal = ((Protocolo1.WSOperaciones.WSOperacionesSoap)(this)).obtenerLlavesPublica(inValue);
            return retVal.Body.obtenerLlavesPublicaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Protocolo1.WSOperaciones.obtenerLlavesPublicaResponse> Protocolo1.WSOperaciones.WSOperacionesSoap.obtenerLlavesPublicaAsync(Protocolo1.WSOperaciones.obtenerLlavesPublicaRequest request) {
            return base.Channel.obtenerLlavesPublicaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Protocolo1.WSOperaciones.obtenerLlavesPublicaResponse> obtenerLlavesPublicaAsync(string telefono) {
            Protocolo1.WSOperaciones.obtenerLlavesPublicaRequest inValue = new Protocolo1.WSOperaciones.obtenerLlavesPublicaRequest();
            inValue.Body = new Protocolo1.WSOperaciones.obtenerLlavesPublicaRequestBody();
            inValue.Body.telefono = telefono;
            return ((Protocolo1.WSOperaciones.WSOperacionesSoap)(this)).obtenerLlavesPublicaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Protocolo1.WSOperaciones.VerificarCertificadoResponse Protocolo1.WSOperaciones.WSOperacionesSoap.VerificarCertificado(Protocolo1.WSOperaciones.VerificarCertificadoRequest request) {
            return base.Channel.VerificarCertificado(request);
        }
        
        public bool VerificarCertificado(string telefono) {
            Protocolo1.WSOperaciones.VerificarCertificadoRequest inValue = new Protocolo1.WSOperaciones.VerificarCertificadoRequest();
            inValue.Body = new Protocolo1.WSOperaciones.VerificarCertificadoRequestBody();
            inValue.Body.telefono = telefono;
            Protocolo1.WSOperaciones.VerificarCertificadoResponse retVal = ((Protocolo1.WSOperaciones.WSOperacionesSoap)(this)).VerificarCertificado(inValue);
            return retVal.Body.VerificarCertificadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Protocolo1.WSOperaciones.VerificarCertificadoResponse> Protocolo1.WSOperaciones.WSOperacionesSoap.VerificarCertificadoAsync(Protocolo1.WSOperaciones.VerificarCertificadoRequest request) {
            return base.Channel.VerificarCertificadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Protocolo1.WSOperaciones.VerificarCertificadoResponse> VerificarCertificadoAsync(string telefono) {
            Protocolo1.WSOperaciones.VerificarCertificadoRequest inValue = new Protocolo1.WSOperaciones.VerificarCertificadoRequest();
            inValue.Body = new Protocolo1.WSOperaciones.VerificarCertificadoRequestBody();
            inValue.Body.telefono = telefono;
            return ((Protocolo1.WSOperaciones.WSOperacionesSoap)(this)).VerificarCertificadoAsync(inValue);
        }
    }
}
